# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(db_column='cabinet_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='cabinet_name', max_length=100, null=True)),
                ('size', models.IntegerField(blank=True, db_column='cabinet_size', null=True)),
            ],
            options={
                'db_table': 'cabinet',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(db_column='ha_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='ha_name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'vm_cluster',
            },
        ),
        migrations.CreateModel(
            name='Cobbler',
            fields=[
                ('id', models.AutoField(db_column='cobbler_id', primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cobbler',
            },
        ),
        migrations.CreateModel(
            name='Contacter',
            fields=[
                ('id', models.AutoField(db_column='contacter_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dept', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'contacter',
            },
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(db_column='dc_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='dc_name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'vm_datacenter',
            },
        ),
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.AutoField(db_column='datastore_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='datastore_name', max_length=50, null=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('free_space', models.CharField(blank=True, max_length=50, null=True)),
                ('provisioned', models.CharField(blank=True, max_length=50, null=True)),
                ('uncommitted', models.CharField(blank=True, max_length=50, null=True)),
                ('hosts', models.IntegerField(blank=True, default=0, null=True)),
                ('vms', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'vm_datastore',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(db_column='disk_id', primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, db_column='disk_name', max_length=30, null=True)),
                ('dtype', models.CharField(blank=True, db_column='disk_model', max_length=30, null=True)),
                ('raid_name', models.CharField(blank=True, max_length=100, null=True)),
                ('raid_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, db_column='disk_size', max_length=30, null=True)),
            ],
            options={
                'db_table': 'disk',
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(db_column='environment_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='environment_name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'environment',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(db_column='guest_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='guest_name', max_length=50, null=True)),
                ('annotation', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu', models.IntegerField(blank=True, default=0, null=True)),
                ('diskGB', models.CharField(blank=True, max_length=50, null=True)),
                ('folder', models.CharField(blank=True, max_length=50, null=True)),
                ('mem', models.IntegerField(blank=True, default=0, null=True)),
                ('ostype', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_template', models.BooleanField(default=False)),
                ('datastore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Datastore')),
            ],
            options={
                'db_table': 'vm_guest',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(db_column='host_id', primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Cluster')),
            ],
            options={
                'db_table': 'vm_host',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(db_column='idc_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='idc_name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'idc',
            },
        ),
        migrations.CreateModel(
            name='Nic',
            fields=[
                ('id', models.AutoField(db_column='nic_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nic_name', max_length=20, null=True)),
                ('mac', models.CharField(blank=True, db_column='mac', max_length=50, null=True)),
                ('model', models.CharField(blank=True, db_column='nic_model', max_length=100, null=True)),
            ],
            options={
                'db_table': 'nic',
            },
        ),
        migrations.CreateModel(
            name='PreSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('profile', models.CharField(blank=True, max_length=50, null=True)),
                ('progress', models.IntegerField(blank=True, default=-1, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'pre_system',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.CharField(db_column='server_id', max_length=100, primary_key=True, serialize=False)),
                ('sn', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=100, null=True)),
                ('cpu_sockets', models.IntegerField(blank=True, null=True)),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('cpu_threads', models.IntegerField(blank=True, null=True)),
                ('mem_size', models.IntegerField(blank=True, null=True)),
                ('mem_total_slots', models.IntegerField(blank=True, null=True)),
                ('mem_free_slots', models.IntegerField(blank=True, null=True)),
                ('raid_adapter', models.CharField(blank=True, max_length=200, null=True)),
                ('raid_adapter_slot', models.CharField(blank=True, max_length=20, null=True)),
                ('ipmi_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ipmi_user', models.CharField(blank=True, max_length=30, null=True)),
                ('ipmi_pass', models.CharField(blank=True, max_length=30, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('pxe_mac', models.CharField(blank=True, max_length=30, null=True)),
                ('pxe_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=30, null=True)),
                ('model', models.CharField(blank=True, max_length=30, null=True)),
                ('prod_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('power', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Cabinet')),
                ('contacter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Contacter')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Environment')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'server',
            },
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(db_column='server_status_id', primary_key=True, serialize=False)),
                ('status_type', models.CharField(blank=True, db_column='server_status_type', max_length=50, null=True)),
                ('name', models.CharField(blank=True, db_column='server_status_name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'server_status',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(db_column='tag_id', primary_key=True, serialize=False)),
                ('tag_type', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='Vcenter',
            fields=[
                ('id', models.AutoField(db_column='vc_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='vc_name', max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('port', models.CharField(default='443', max_length=10)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'vcenter',
            },
        ),
        migrations.CreateModel(
            name='Vnet',
            fields=[
                ('mac', models.CharField(db_column='mac', max_length=50, primary_key=True, serialize=False)),
                ('connected', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('netlabel', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Guest')),
            ],
            options={
                'db_table': 'vm_guest_net',
            },
        ),
        migrations.AddField(
            model_name='server',
            name='serverstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.ServerStatus'),
        ),
        migrations.AddField(
            model_name='server',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Tag'),
        ),
        migrations.AddField(
            model_name='presystem',
            name='server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='installation.Server'),
        ),
        migrations.AddField(
            model_name='nic',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Server'),
        ),
        migrations.AddField(
            model_name='host',
            name='server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Server'),
        ),
        migrations.AddField(
            model_name='guest',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Host'),
        ),
        migrations.AddField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='installation.Server'),
        ),
        migrations.AddField(
            model_name='datastore',
            name='vcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Vcenter'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='vcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Vcenter'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Datacenter'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Idc'),
        ),
    ]
