# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='installation.Server'),
        ),
    ]
