# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_auto_20170808_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
