# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_auto_20170624_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
