# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0003_server_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='progress',
        ),
        migrations.AlterField(
            model_name='server',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
