# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0004_auto_20170628_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('profile', models.CharField(blank=True, max_length=50, null=True)),
                ('progress', models.IntegerField(blank=True, default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='installation.Server')),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'pre_system',
            },
        ),
    ]
