# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0005_presystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='presystem',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='presystem',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
