# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0006_auto_20170628_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presystem',
            name='server',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='installation.Server'),
        ),
    ]
