# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0007_auto_20170628_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk',
            old_name='model',
            new_name='dtype',
        ),
        migrations.RenameField(
            model_name='disk',
            old_name='name',
            new_name='path',
        ),
        migrations.AddField(
            model_name='nic',
            name='name',
            field=models.CharField(blank=True, db_column='nic_name', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nic',
            name='mac',
            field=models.CharField(blank=True, db_column='mac', max_length=50, null=True),
        ),
    ]
