# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0008_auto_20170629_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='status',
        ),
    ]
