# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0009_remove_disk_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presystem',
            name='progress',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
