# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0010_auto_20170703_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(db_column='ha_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='ha_name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'vm_cluster',
            },
        ),
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.AutoField(db_column='dc_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='dc_name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'vm_datacenter',
            },
        ),
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.AutoField(db_column='datastore_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='datastore_name', max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('free_space', models.CharField(blank=True, max_length=50, null=True)),
                ('provisioned', models.CharField(blank=True, max_length=50, null=True)),
                ('uncommitted', models.CharField(blank=True, max_length=50, null=True)),
                ('hosts', models.IntegerField(blank=True, default=0, null=True)),
                ('vms', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'vm_datastore',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(db_column='guest_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='guest_name', max_length=50, null=True)),
                ('annotation', models.CharField(blank=True, max_length=200, null=True)),
                ('cpu', models.IntegerField(blank=True, default=0, null=True)),
                ('diskGB', models.CharField(blank=True, max_length=50, null=True)),
                ('folder', models.CharField(blank=True, max_length=50, null=True)),
                ('mem', models.IntegerField(blank=True, default=0, null=True)),
                ('ostype', models.CharField(blank=True, max_length=50, null=True)),
                ('path', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('datastore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Datastore')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Cluster')),
            ],
            options={
                'db_table': 'vm_guest',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(db_column='host_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='host_name', max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Cluster')),
                ('server', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Server')),
            ],
            options={
                'db_table': 'vm_host',
            },
        ),
        migrations.CreateModel(
            name='Vcenter',
            fields=[
                ('id', models.AutoField(db_column='vc_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='vc_name', max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'vcenter',
            },
        ),
        migrations.CreateModel(
            name='Vnet',
            fields=[
                ('mac', models.CharField(db_column='mac', max_length=50, primary_key=True, serialize=False)),
                ('connected', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('netlabel', models.CharField(blank=True, max_length=100, null=True)),
                ('prefix', models.CharField(blank=True, max_length=50, null=True)),
                ('Guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Guest')),
            ],
            options={
                'db_table': 'vm_guest_net',
            },
        ),
        migrations.AddField(
            model_name='datastore',
            name='vcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Vcenter'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='vcenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Vcenter'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Datacenter'),
        ),
    ]
