# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0011_auto_20170706_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='name',
        ),
    ]
