# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0012_remove_host_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='prod_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
