# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0013_server_prod_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Host'),
        ),
    ]
