# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0016_remove_datastore_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
