# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0017_guest_is_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcenter',
            name='port',
            field=models.CharField(default='443', max_length=10),
        ),
    ]
