# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0018_vcenter_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobbler',
            fields=[
                ('id', models.AutoField(db_column='cobbler_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('dhcp', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'cobbler',
            },
        ),
    ]
