# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0019_cobbler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobbler',
            name='dhcp',
        ),
        migrations.RemoveField(
            model_name='cobbler',
            name='name',
        ),
    ]
