# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltFun',
            fields=[
                ('id', models.AutoField(db_column='salt_fun_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'salt_fun',
            },
        ),
    ]
