# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltJob',
            fields=[
                ('id', models.AutoField(db_column='salt_jid', primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.CharField(blank=True, max_length=100, null=True)),
                ('act', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'salt_jobs',
            },
        ),
    ]
