# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='fqdn',
        ),
        migrations.AlterField(
            model_name='system',
            name='id',
            field=models.CharField(db_column='system_id', max_length=100, primary_key=True, serialize=False),
        ),
    ]
