# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0002_saltjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saltjob',
            old_name='act',
            new_name='arg',
        ),
        migrations.AddField(
            model_name='saltjob',
            name='fun',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
