# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0003_auto_20170725_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaltJob',
        ),
        migrations.AddField(
            model_name='system',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
