# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0004_auto_20170727_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='status',
            new_name='minion_status',
        ),
        migrations.AddField(
            model_name='system',
            name='power_status',
            field=models.BooleanField(default=True),
        ),
    ]
