# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0004_salt_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaltState',
            fields=[
                ('id', models.AutoField(db_column='salt_state_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'salt_state',
            },
        ),
    ]
