# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0005_auto_20170728_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
