# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0005_saltstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='saltstate',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
