# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0006_saltstate_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unique=True)),
                ('port', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'service_host',
            },
        ),
    ]
