# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0006_system_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
