# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('opsdb', '0007_auto_20170728_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='application',
            new_name='applications',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='application',
            new_name='applications',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='business',
            new_name='businesses',
        ),
        migrations.AddField(
            model_name='application',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='business',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
