# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0007_servicehost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salt',
        ),
        migrations.AlterField(
            model_name='servicehost',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
