# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0008_auto_20170804_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='businesses',
        ),
        migrations.AlterModelTable(
            name='hostgroup',
            table='hostgroup',
        ),
    ]
