# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0009_auto_20170804_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hostgroup',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='saltstate',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='system',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
