# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0010_auto_20170807_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='hostgroup',
        ),
        migrations.AddField(
            model_name='system',
            name='hostgroup',
            field=models.ManyToManyField(to='opsdb.HostGroup'),
        ),
    ]
