# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
        ('opsdb', '0011_auto_20170807_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='environment',
        ),
        migrations.AddField(
            model_name='business',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='installation.Environment'),
        ),
    ]
