# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0012_auto_20170807_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='hostgroup',
            new_name='hostgroups',
        ),
    ]
