# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opsdb', '0013_auto_20170808_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='applications',
        ),
        migrations.AddField(
            model_name='application',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='opsdb.Business'),
        ),
    ]
