# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170802_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
