# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170803_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='role',
            new_name='roles',
        ),
    ]
