# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170803_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='wechat',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='comment',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
