# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_expired',
            field=models.DateTimeField(null=True),
        ),
    ]
